//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataCollectionEntities : DbContext
    {
        public DataCollectionEntities()
            : base("name=DataCollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public DbSet<PersonInfo> PersonInfoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TM_DailySheet> TM_DailySheet { get; set; }
        public DbSet<TM_Department> TM_Department { get; set; }
        public DbSet<TM_Projects> TM_Projects { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ViewPersonCompanyInfo> ViewPersonCompanyInfoes { get; set; }
    }
}
