//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInfo
    {
        public int PID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Address { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string EmailCompany { get; set; }
        public string EmailPersonal { get; set; }
        public string PhoneOffice { get; set; }
        public string PhonePersonal { get; set; }
        public string Linkedin { get; set; }
        public string Tags { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual CompanyInfo CompanyInfo { get; set; }
    }
}
